import { States } from '../models/states';

export const ReturnStateList: States[] = [
    {StateID: 1, Description: 'Aguascalientes'},
    {StateID: 2, Description: 'Baja California'},
    {StateID: 3, Description: 'Baja California Sur'},
    {StateID: 4, Description: 'Campeche'},
    {StateID: 5, Description: 'Chiapas'},
    {StateID: 6, Description: 'Chihuahua'},
    {StateID: 7, Description: 'Coahuila de Zaragoza'},
    {StateID: 8, Description: 'Colima'},
    {StateID: 8, Description: 'Ciudad de México'},
    {StateID: 9, Description: 'Durango'},
    {StateID: 10, Description: 'Estado de México'},
    {StateID: 11, Description: 'Guanajuato'},
    {StateID: 12, Description: 'Guerrero'},
    {StateID: 13, Description: 'Hidalgo'},
    {StateID: 14, Description: 'Jalisco'},
    {StateID: 15, Description: 'Michoacán de Ocampo'},
    {StateID: 16, Description: 'Morelos'},
    {StateID: 17, Description: 'Nayarit'},
    {StateID: 18, Description: 'Nuevo León'},
    {StateID: 19, Description: 'Oaxaca'},
    {StateID: 20, Description: 'Puebla'},
    {StateID: 21, Description: 'Querétaro'},
    {StateID: 22, Description: 'Quintana Roo'},
    {StateID: 23, Description: 'San Luis Potosí'},
    {StateID: 24, Description: 'Sinaloa'},
    {StateID: 25, Description: 'Sonora'},
    {StateID: 26, Description: 'Tabasco'},
    {StateID: 27, Description: 'Tamaulipas'},
    {StateID: 28, Description: 'Tlaxcala'},
    {StateID: 29, Description: 'Veracruz de Ignacio de la Llave'},
    {StateID: 30, Description: 'Yucatán'},
    {StateID: 31, Description: 'Zacatecas'}
];